name: 'Cache'
description: 'Cache .conan directories'
author: 'TurtleBrowser'
inputs:
  bot_name:
    description: 'The name of the GitHub bot'
    required: true
  bot_token:
    description: 'The personal access token of the GitHub bot'
    required: true
  cache_name:
    description: 'The GitHub repo used for this cache'
    required: true
  key:
    description: 'An explicit key'
    required: true
  fallback:
    description: 'A fallback key'
    required: false
  path:
    description: 'Path to the directory that contains .conan - defaults to ~/'
    required: false
  branch:
    description: 'Branch on the cache repo - defaults to master'
    required: false
outputs:
  cache-hit:
    description: 'Cache a hit on a key: no hit (0), explicit key (1), fallback key (2)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bot_name }}
    - ${{ inputs.bot_token }}
    - ${{ inputs.cache_name }}
    - ${{ inputs.key }}
    - ${{ inputs.fallback }}
    - ${{ inputs.path }}
    - ${{ inputs.branch }}
  entrypoint: '/restore.sh'
  post-entrypoint: '/save.sh'
  post-if: 'success()'
branding:
  icon: 'archive'
  color: 'green'
