name: 'Cache'
description: 'Cache .conan directories'
author: 'TurtleBrowser'
inputs:
  path:
    description: 'Path to the directory that contains .conan'
    required: true
  key:
    description: 'An explicit key'
    required: true
  fallback:
    description: 'A fallback key'
    required: false
outputs:
  cache-hit:
    description: 'Cache a hit on a key: no hit (0), explicit key (1), fallback key (2)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.key }}
    - ${{ inputs.fallback }}
branding:
  icon: 'archive'
  color: 'green'
