name: 'Cache'
description: 'Cache .conan directories'
author: 'TurtleBrowser'
inputs:
  bot_name:
    description: 'The name of the GitHub bot'
    required: true
  bot_token:
    description: 'The personal access token of the GitHub bot'
    required: true
  cache_name:
    description: 'The GitHub repo used for this cache'
    required: true
  key:
    description: 'An explicit key'
    required: true
  target_os:
    description: 'Target OS if different from host OS'
    required: false
outputs:
  cache-hit:
    description: 'Cache a hit on a key: no hit (0), explicit key (1), fallback key (2)'
runs:
  using: 'node12'
  main: 'restore.js'
  post: 'save.js'
  #post-if: 'success()'
branding:
  icon: 'archive'
  color: 'green'
