on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/conan/"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Conan modules
        id: cache-conan
        uses: ./ # Uses an action in the root directory
        with:
          bot_name: ${{ secrets.BOT_NAME }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          cache_name: turtlebrowser/conan-cache-linux
          key: test
          target_os: Test

      - name: Set CONAN_USER_HOME ownership to current user
        run: sudo chown -R $(id -u):$(id -g) ${{ env.CONAN_USER_HOME }}

      - name: Did we hit the cache?
        run: echo "cache-hit was ${{ env.cache-hit }}"

      - name: Get Conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan --upgrade
      
      - name: Fix Path on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: echo "::add-path::/home/runner/.local/bin"

      - name: Put something in the .conan
        if: ${{ env.cache-hit }} == 0
        run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

      - name: Print branch
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"

      - name: Clean up Conan
        run: conan remove -f "*" --builds --src --system-reqs
