name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/conan/"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Conan modules
        id: cache-conan
        uses: ./ # Uses an action in the root directory
        with:
          bot_name: ${{ secrets.BOT_NAME }}
          bot_token: ${{ secrets.BOT_TOKEN }}
          cache_name: turtlebrowser/conan-cache-turtlebrowser
          key: test_${{ runner.os }}-${{ matrix.os }}-${{ hashFiles('restore.sh') }}-${{ hashFiles('save.sh') }}
          target_os: Test
          lfs_limit: 60

      - name: Did we hit the cache?
        run: echo "cache-hit was ${{ steps.cache-conan.outputs.cache-hit }}"

      - name: Get Conan
        run: |
          pip3 install wheel setuptools
          pip3 install conan --upgrade
      
      - name: Fix Path on Ubuntu
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-18.04' ||  matrix.os == 'ubuntu-16.04' || matrix.os == 'ubuntu-latest' 
        run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Put something in the .conan
        if: ${{ steps.cache-conan.outputs.cache-hit == 0 }}
        run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

      - name: Print branch
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"
